'use client'

import useSWR from 'swr'
import Link from 'next/link'
import { ArrowUpRight, BarChart3, Search, Trophy } from 'lucide-react'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'

export default function LeaderboardPage() {
  const supabase = getSupabaseBrowserClient()
  const { data, isLoading } = useSWR(supabase ? 'leaderboard-tokens' : null, async () => { const { data } = await supabase!.from('tokens').select('contract_address,name,symbol,price,market_cap,volume_24h,progress,verified').order('volume_24h', { ascending: false }).limit(100); return data ?? [] })
  return <main className="min-h-screen bg-[#0b0f16] px-5 py-8 text-white lg:px-10"><div className="mx-auto max-w-6xl"><Link href="/" className="text-xs text-[#8eb1eb]">← LUNAFAD</Link><div className="mt-10 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[11px] uppercase tracking-[.2em] text-[#71d7ba]">Market pulse</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Leaderboard</h1><p className="mt-3 text-sm text-[#8c98ab]">Rankings sourced from indexed SVP Chain activity.</p></div><div className="flex gap-2"><button className="rounded-lg bg-[#345d9d] px-4 py-2 text-xs">24h</button><button className="rounded-lg border border-white/10 px-4 py-2 text-xs">7d</button></div></div><div className="mt-8 flex items-center gap-3 rounded-xl border border-white/10 bg-[#111722] px-4 py-3"><Search className="size-4 text-[#71809a]" /><input className="w-full bg-transparent text-sm outline-none" placeholder="Search rankings" /></div><div className="mt-5 overflow-hidden rounded-xl border border-white/10 bg-[#111722]"><div className="grid grid-cols-[50px_1fr_130px_130px_120px] gap-4 border-b border-white/10 px-5 py-3 text-[10px] uppercase tracking-wider text-[#71809a]"><span>#</span><span>Token</span><span>Market cap</span><span>Volume 24h</span><span>Progress</span></div>{isLoading ? <div className="p-8 text-sm text-[#71809a]">Loading indexed tokens…</div> : data?.length ? data.map((token, i) => <Link href={`/token/${token.contract_address}`} key={token.contract_address} className="grid grid-cols-[50px_1fr_130px_130px_120px] items-center gap-4 border-b border-white/[.05] px-5 py-4 hover:bg-white/[.03]"><span className="flex items-center gap-2 text-sm text-[#71809a]">{i < 3 ? <Trophy className="size-3 text-[#d8b36e]" /> : null}{String(i + 1).padStart(2, '0')}</span><span><b className="block text-sm">{token.name}</b><small className="text-[#71809a]">{token.symbol}</small></span><span className="text-xs">${Number(token.market_cap ?? 0).toLocaleString()}</span><span className="text-xs">${Number(token.volume_24h ?? 0).toLocaleString()}</span><span className="flex items-center gap-2 text-xs"><span className="h-1.5 flex-1 rounded-full bg-white/10"><span className="block h-full rounded-full bg-[#71d7ba]" style={{ width: `${Math.min(Number(token.progress ?? 0), 100)}%` }} /></span><ArrowUpRight className="size-3" /></span></Link>) : <div className="p-10 text-center text-sm text-[#71809a]"><BarChart3 className="mx-auto mb-3 size-7" />No indexed tokens yet. Deploy the first token.</div>}</div></div></main>
}
