'use client'

import { useState } from 'react'
import { AlertTriangle, ClipboardCheck, FileSearch, Flag, LockKeyhole, ShieldCheck, type LucideIcon } from 'lucide-react'
import { PageFrame, SectionHeading } from '@/components/app-header'

const queues = ['All cases', 'Token review', 'Reports', 'Suspicious activity', 'Indexer failures']
const metrics: Array<[string, string, string, LucideIcon]> = [['Open cases', '—', 'Awaiting indexed queue', AlertTriangle], ['Verified creators', '—', 'Verified identity records', ShieldCheck], ['Risk flags', '—', 'Rules engine output', Flag], ['Audit events', '—', 'Immutable event ledger', ClipboardCheck]]
const controls = [
  ['Contract verification', 'Ownership, bytecode, and deployment provenance checks', 'Ready'],
  ['Liquidity safety', 'LP lock, reserve depth, and graduation review', 'Ready'],
  ['Trading anomaly', 'Velocity, holder concentration, and wash-trade signals', 'Monitor'],
  ['Content moderation', 'Metadata quality, impersonation, and abuse reports', 'Ready'],
]

export default function AdminPage() {
  const [queue, setQueue] = useState('All cases')
  return <PageFrame><SectionHeading eyebrow="Operations console" title="Risk & compliance" description="A controlled workspace for review queues, risk signals, indexer health, and auditable decisions. Production records appear after the admin data source is connected." /><div className="grid gap-4 md:grid-cols-4">{metrics.map(([label, value, hint, Icon]) => <div key={String(label)} className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><Icon className="size-4 text-[#8eb1eb]" /><p className="mt-5 text-xs text-[#71809a]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-2 text-[11px] text-[#71809a]">{hint}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-2 text-[10px] uppercase tracking-wider text-[#71809a]"><span className="rounded-full border border-[#71d7ba]/20 bg-[#71d7ba]/[0.06] px-2.5 py-1 text-[#9de8d1]">Admin source: unavailable</span><span className="rounded-full border border-white/[0.08] px-2.5 py-1">No fabricated cases</span><span className="rounded-full border border-white/[0.08] px-2.5 py-1">Audit required</span></div><section className="mt-6 rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium">Review queue</p><p className="mt-1 text-xs text-[#71809a]">Cases are intentionally empty until the moderated event source is available.</p></div><div className="flex flex-wrap gap-2">{queues.map(item => <button key={item} onClick={() => setQueue(item)} className={`rounded-lg px-3 py-2 text-xs ${queue === item ? 'bg-[#345d9d] text-white' : 'border border-white/[0.08] text-[#8c98ab]'}`}>{item}</button>)}</div></div><div className="mt-6 rounded-xl border border-dashed border-white/[0.1] px-6 py-12 text-center"><FileSearch className="mx-auto size-5 text-[#71809a]" /><p className="mt-3 text-sm">No {queue.toLowerCase()} in this environment</p><p className="mt-2 text-xs text-[#71809a]">Connect the admin event stream to review real cases without fabricating records.</p></div></section><div className="mt-6 grid gap-4 lg:grid-cols-2">{controls.map(([title, body, status]) => <div key={title} className="flex items-start gap-4 rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-[#71d7ba]/10"><LockKeyhole className="size-4 text-[#71d7ba]" /></div><div><div className="flex items-center gap-3"><p className="text-sm font-medium">{title}</p><span className="rounded-full bg-[#71d7ba]/10 px-2 py-1 text-[10px] text-[#71d7ba]">{status}</span></div><p className="mt-2 text-xs leading-5 text-[#71809a]">{body}</p></div></div>)}</div></PageFrame>
}
