'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import useSWR from 'swr'
import { BarChart3, CheckCircle2, ExternalLink, FileText, Landmark, RefreshCw, Rocket, ShieldCheck, WalletCards } from 'lucide-react'
import { PageFrame } from '@/components/app-header'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'

type Token = { contract_address: string; name: string; symbol: string; status: string; market_cap: number | null; volume_24h: number | null; progress: number | null; created_at?: string | null; verified?: boolean | null }
type Tab = 'launches' | 'analytics' | 'fees' | 'checklist'

export default function CreatorPage() {
  const supabase = getSupabaseBrowserClient()
  const creator = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('address') : null
  const [tab, setTab] = useState<Tab>('launches')
  const { data, error, isLoading, mutate } = useSWR(supabase && creator ? ['creator-studio', creator] : null, async () => { const { data, error } = await supabase!.from('tokens').select('contract_address,name,symbol,status,market_cap,volume_24h,progress,created_at,verified').eq('creator_address', creator!).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Token[] })
  const totals = useMemo(() => (data ?? []).reduce((result, token) => ({ marketCap: result.marketCap + Number(token.market_cap ?? 0), volume: result.volume + Number(token.volume_24h ?? 0) }), { marketCap: 0, volume: 0 }), [data])
  return <PageFrame active="Portfolio"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-semibold tracking-[0.24em] text-[#71d7ba]">CREATOR STUDIO</p><h1 className="text-4xl font-semibold tracking-tight">Launch with confidence</h1><p className="mt-3 max-w-2xl text-sm text-[#8c98ab]">Manage launches, monitor indexed performance, and keep every creator action reviewable.</p></div><div className="flex gap-2"><Link href="/create" className="flex items-center gap-2 rounded-lg bg-[#f1f5fa] px-4 py-2 text-sm font-semibold text-[#172033]"><Rocket className="size-4" />New launch</Link><button type="button" onClick={() => mutate()} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-[#b9c3d1]"><RefreshCw className="size-4" />Refresh</button></div></header>{!creator ? <Empty title="Connect a creator wallet" body="Creator analytics are scoped to an on-chain address. Open this page with ?address=0x... to load deployed tokens." /> : <><div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric label="Launches" value={String(data?.length ?? 0)} icon={Rocket} /><Metric label="Indexed market cap" value={data ? `$${totals.marketCap.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : '—'} icon={BarChart3} /><Metric label="24h volume" value={data ? `$${totals.volume.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : '—'} icon={WalletCards} /></div><section className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-medium">Creator workspace</h2><p className="mt-1 text-xs text-[#718096]">Indexed token data for {creator.slice(0, 8)}…{creator.slice(-6)}</p></div><nav className="flex max-w-full overflow-x-auto rounded-lg border border-white/10 p-1" aria-label="Creator sections">{([['launches','Launches',Rocket],['analytics','Analytics',BarChart3],['fees','Fees',WalletCards],['checklist','Launch checklist',FileText]] as const).map(([key,label,Icon]) => <button type="button" key={key} onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-xs ${tab === key ? 'bg-[#345d9d] text-white' : 'text-[#8c98ab]'}`}><Icon className="size-3.5" />{label}</button>)}</nav></div>{tab === 'launches' && <Launches data={data} isLoading={isLoading} error={error} />}{tab === 'analytics' && <Analytics data={data ?? []} />}{tab === 'fees' && <Fees />}{tab === 'checklist' && <Checklist />}</section></>}</div></PageFrame>
}

function Launches({ data, isLoading, error }: { data?: Token[]; isLoading: boolean; error?: Error }) { if (isLoading) return <State text="Loading creator launches…" />; if (error) return <State text="Unable to load launches. Refresh and try again." danger />; if (!data?.length) return <Empty title="No indexed launches yet" body="Deploy your first token to start building a creator portfolio." />; return <div className="grid gap-4 md:grid-cols-2">{data.map(token => <article key={token.contract_address} className="rounded-xl border border-white/[0.07] bg-[#0b0f16] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{token.name} <span className="text-[#718096]">${token.symbol}</span></h3><p className="mt-2 font-mono text-xs text-[#718096]">{token.contract_address.slice(0, 10)}…{token.contract_address.slice(-8)}</p></div><span className="rounded-full border border-[#71d7ba]/30 bg-[#71d7ba]/10 px-2 py-1 text-[10px] uppercase text-[#71d7ba]">{token.status}</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#71d7ba]" style={{ width: `${Math.min(100, Math.max(0, Number(token.progress ?? 0)))}%` }} /></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><p className="text-[#718096]">Market cap</p><p className="mt-1 text-white">${Number(token.market_cap ?? 0).toLocaleString()}</p></div><div><p className="text-[#718096]">24h volume</p><p className="mt-1 text-white">${Number(token.volume_24h ?? 0).toLocaleString()}</p></div><div><p className="text-[#718096]">Verified</p><p className="mt-1 text-[#71d7ba]">{token.verified ? 'Yes' : 'Pending'}</p></div></div><Link href={`/token/${token.contract_address}`} className="mt-5 inline-flex items-center gap-2 text-xs text-[#8eb1eb]">Open token <ExternalLink className="size-3.5" /></Link></article>)}</div> }
function Analytics({ data }: { data: Token[] }) { const graduated = data.filter(token => token.status === 'graduated').length; return <div className="grid gap-4 md:grid-cols-3"><Metric label="Graduated launches" value={String(graduated)} icon={CheckCircle2} /><Metric label="Average progress" value={data.length ? `${(data.reduce((sum, token) => sum + Number(token.progress ?? 0), 0) / data.length).toFixed(1)}%` : '—'} icon={BarChart3} /><Metric label="Data source" value="Indexed" icon={ShieldCheck} /><div className="md:col-span-3 rounded-xl border border-[#d9b878]/20 bg-[#d9b878]/[0.06] p-4 text-sm text-[#d9b878]">Analytics are based on confirmed indexed token records. Add the event indexer to unlock holder cohorts, retention, fees, and historical chart series.</div></div> }
function Fees() { return <div className="rounded-xl border border-dashed border-white/15 p-10 text-center"><WalletCards className="mx-auto mb-4 text-[#d9b878]" /><h3 className="font-medium">Fee ledger is not indexed yet</h3><p className="mx-auto mt-2 max-w-md text-sm text-[#718096]">Claimable fees and payout history will appear here after the fee events and creator ledger are connected to the indexer.</p></div> }
function Checklist() { return <div className="grid gap-3 sm:grid-cols-2">{['Wallet connected to SVP Chain','Token metadata reviewed','Supply and decimals confirmed','Deployment transaction confirmed','TokenCreated event indexed','Launch page shared'].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-[#0b0f16] p-4 text-sm"><span className={`flex size-6 items-center justify-center rounded-full text-xs ${index < 2 ? 'bg-[#71d7ba]/15 text-[#71d7ba]' : 'bg-white/[0.06] text-[#718096]'}`}>{index < 2 ? '✓' : index + 1}</span><span className="text-[#c3ccda]">{item}</span></div>)}</div> }
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Rocket }) { return <div className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><Icon className="size-4 text-[#71d7ba]" /><p className="mt-4 text-xs text-[#718096]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div> }
function Empty({ title, body }: { title: string; body: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-12 text-center"><Landmark className="mx-auto mb-4 text-[#71d7ba]" /><h2 className="font-medium">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[#718096]">{body}</p></div> }
function State({ text, danger = false }: { text: string; danger?: boolean }) { return <p className={`py-12 text-center text-sm ${danger ? 'text-[#e87984]' : 'text-[#8c98ab]'}`}>{text}</p> }
