'use client'

import Link from 'next/link'
import useSWR from 'swr'
import { ExternalLink, Landmark, RefreshCw } from 'lucide-react'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'

type Token = { contract_address: string; name: string; symbol: string; status: string; market_cap: number | null; volume_24h: number | null; progress: number | null }
export default function CreatorPage() {
  const supabase = getSupabaseBrowserClient()
  const creator = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('address') : null
  const { data, error, isLoading, mutate } = useSWR(supabase && creator ? ['creator-tokens', creator] : null, async () => { const { data, error } = await supabase!.from('tokens').select('contract_address,name,symbol,status,market_cap,volume_24h,progress').eq('creator_address', creator!).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Token[] })
  return <main className="min-h-screen bg-[#0b0f16] px-5 pb-16 pt-28 text-white lg:px-10"><div className="mx-auto max-w-6xl"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-semibold tracking-[0.24em] text-[#71d7ba]">CREATOR STUDIO</p><h1 className="text-4xl font-semibold tracking-tight">Your launches</h1><p className="mt-3 text-sm text-[#8c98ab]">Manage deployed tokens and monitor the metrics that matter.</p></div><button onClick={() => mutate()} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-[#b9c3d1]"><RefreshCw data-icon="inline-start" />Refresh</button></div>{!creator ? <div className="rounded-2xl border border-dashed border-white/15 bg-[#111722] p-12 text-center"><Landmark className="mx-auto mb-4 text-[#71d7ba]" /><h2 className="font-medium">Connect a creator wallet</h2><p className="mx-auto mt-2 max-w-md text-sm text-[#718096]">Creator analytics are scoped to an on-chain address. Open this page with ?address=0x... to load deployed tokens.</p></div> : isLoading ? <p className="text-sm text-[#8c98ab]">Loading creator dashboard…</p> : error ? <p className="text-sm text-[#e87984]">Unable to load creator tokens.</p> : data?.length ? <div className="grid gap-4 md:grid-cols-2">{data.map(token => <article key={token.contract_address} className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{token.name} <span className="text-[#718096]">${token.symbol}</span></h2><p className="mt-2 font-mono text-xs text-[#718096]">{token.contract_address.slice(0, 10)}…{token.contract_address.slice(-8)}</p></div><span className="rounded-full border border-[#71d7ba]/30 bg-[#71d7ba]/10 px-2 py-1 text-[10px] uppercase text-[#71d7ba]">{token.status}</span></div><div className="mt-6 grid grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-[#718096]">Market cap</p><p className="mt-1">${Number(token.market_cap ?? 0).toLocaleString()}</p></div><div><p className="text-xs text-[#718096]">Volume</p><p className="mt-1">${Number(token.volume_24h ?? 0).toLocaleString()}</p></div><div><p className="text-xs text-[#718096]">Progress</p><p className="mt-1">{Number(token.progress ?? 0).toFixed(1)}%</p></div></div><Link href={`/token/${token.contract_address}`} className="mt-6 inline-flex items-center gap-2 text-sm text-[#8eb1eb]">Open token detail <ExternalLink data-icon="inline-end" /></Link></article>)}</div> : <div className="rounded-2xl border border-white/[0.08] bg-[#111722] p-12 text-center text-sm text-[#718096]">No deployed tokens indexed for this creator address.</div>}</div></main>
}
