'use client'

import Link from 'next/link'
import { Activity, Bell, Menu, Search, UserRound, Wallet, X } from 'lucide-react'
import { useState } from 'react'
import { useWalletIdentity, walletAddressLabel } from '@/lib/web3/wallet-store'

const links = [['Explore', '/explore'], ['Create token', '/create'], ['Trending', '/trending'], ['Leaderboard', '/leaderboard'], ['Portfolio', '/portfolio']] as const

export function AppHeader({ active }: { active?: string }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const identity = useWalletIdentity()
  const connect = async () => { try { await identity.connect() } catch { /* wallet UI remains disconnected */ } }
  const walletLabel = identity.status === 'wrong-network' ? 'Wrong network' : identity.status === 'error' ? 'Reconnect wallet' : walletAddressLabel(identity.address)
  return <header className="sticky top-0 z-40 border-b border-white/[0.08] bg-[#0b0f16]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1480px] items-center gap-4 px-5 lg:px-8"><Link href="/" className="flex shrink-0 items-center gap-2.5"><img src="/lunafad-mascot.png" alt="LUNAFAD mascot" className="lunafad-mascot-float size-10 rounded-xl object-cover shadow-[0_0_30px_rgba(52,93,157,.35)]" /><span className="text-lg font-black tracking-[-0.06em]">LUNA<span className="text-[#8eb1eb]">FAD</span></span></Link><nav className="hidden items-center gap-1 md:flex">{links.map(([label, href]) => <Link key={href} href={href} className={`rounded-lg px-3 py-2 text-xs transition ${active === label ? 'bg-white/[0.08] text-white' : 'text-[#8190a7] hover:bg-white/[0.04] hover:text-white'}`}>{label}</Link>)}</nav><div className="relative ml-auto hidden w-56 lg:block"><Search className="absolute left-3 top-2.5 size-4 text-[#64738b]" /><input aria-label="Search tokens" placeholder="Search tokens, creators..." className="h-9 w-full rounded-lg border border-white/[0.08] bg-white/[0.035] pl-9 pr-3 text-xs outline-none transition focus:border-[#668bc7]" /></div><Link href="/notifications" aria-label="Notifications" className="hidden size-9 items-center justify-center rounded-lg border border-white/[0.08] text-[#8c98ab] transition hover:text-white sm:flex"><Bell className="size-4" /></Link><Link href="/system-health" aria-label="System health" className="hidden size-9 items-center justify-center rounded-lg border border-white/[0.08] text-[#8c98ab] transition hover:text-white sm:flex"><Activity className="size-4" /></Link><Link href="/settings" aria-label="Account settings" className="hidden size-9 items-center justify-center rounded-lg border border-white/[0.08] text-[#8c98ab] transition hover:text-white sm:flex"><UserRound className="size-4" /></Link><button onClick={connect} disabled={identity.status === 'connecting'} className={`flex h-9 items-center gap-2 rounded-lg px-3.5 text-xs font-medium transition ${identity.status === 'wrong-network' ? 'bg-[#d9b878] text-[#172033]' : 'bg-[#345d9d] text-white hover:bg-[#426fb5]'}`}><Wallet className="size-3.5" />{identity.status === 'connecting' ? 'Connecting...' : walletLabel}</button><button aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)} className="flex size-9 items-center justify-center rounded-lg border border-white/[0.08] text-[#8c98ab] sm:hidden">{menuOpen ? <X className="size-4" /> : <Menu className="size-4" />}</button></div>{menuOpen && <div className="border-t border-white/[0.08] bg-[#0b0f16] px-5 py-4 sm:hidden"><nav className="grid gap-1">{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setMenuOpen(false)} className={`rounded-lg px-3 py-3 text-sm ${active === label ? 'bg-white/[0.08] text-white' : 'text-[#8190a7]'}`}>{label}</Link>)}</nav></div>}</header>
}

export function PageFrame({ active, children }: { active?: string; children: React.ReactNode }) { return <main className="min-h-screen bg-[#0b0f16] text-white"><AppHeader active={active} /><div className="mx-auto max-w-[1480px] px-5 py-8 lg:px-8 lg:py-12">{children}</div></main> }
export function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[#6e9de1]">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#8492a8]">{description}</p></div> }
export function EmptyState({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-dashed border-white/[0.12] bg-white/[0.02] px-6 py-16 text-center"><div className="mx-auto size-2 rounded-full bg-[#71d7ba] shadow-[0_0_24px_#71d7ba]" /><h2 className="mt-5 text-lg font-medium">{title}</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-[#71809a]">{body}</p></div> }
