'use client'

import Link from 'next/link'
import useSWR from 'swr'
import { ArrowUpRight, Crown, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'

type Token = { contract_address: string; name: string; symbol: string; current_price: number | null; market_cap: number | null; volume_24h: number | null; progress: number | null; status: string }
const views = [{ label: 'Market cap', field: 'market_cap' }, { label: 'Volume', field: 'volume_24h' }, { label: 'Curve progress', field: 'progress' }] as const

export default function TrendingPage() {
  const supabase = getSupabaseBrowserClient()
  const [view, setView] = useState<(typeof views)[number]['field']>('market_cap')
  const { data, error, isLoading, mutate } = useSWR(supabase ? ['trending-tokens', view] : null, async () => { const { data, error } = await supabase!.from('tokens').select('contract_address,name,symbol,current_price,market_cap,volume_24h,progress,status').order(view, { ascending: false }).limit(50); if (error) throw error; return (data ?? []) as Token[] })
  return <main className="min-h-screen bg-[#0b0f16] px-5 pb-16 pt-28 text-white lg:px-10"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-semibold tracking-[0.24em] text-[#d8b36e]">MARKET PULSE</p><h1 className="text-4xl font-semibold tracking-tight">Trending leaderboard</h1><p className="mt-3 text-sm text-[#8c98ab]">Rankings are calculated from indexed token metrics, not placeholder data.</p></div><button onClick={() => mutate()} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-[#b9c3d1]"><RefreshCw data-icon="inline-start" />Refresh</button></header><div className="mb-6 flex flex-wrap gap-2">{views.map(item => <button key={item.field} onClick={() => setView(item.field)} className={`rounded-lg px-4 py-2 text-xs ${view === item.field ? 'bg-[#345d9d] text-white' : 'border border-white/10 text-[#8c98ab]'}`}>{item.label}</button>)}</div>{isLoading ? <p className="py-16 text-center text-sm text-[#8c98ab]">Loading rankings…</p> : error ? <p className="py-16 text-center text-sm text-[#e87984]">Unable to load leaderboard data.</p> : data?.length ? <div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-[#111722]"><div className="grid grid-cols-[56px_1fr_130px_130px_120px] gap-4 border-b border-white/[0.08] px-5 py-4 text-[10px] uppercase tracking-wider text-[#718096]"><span>Rank</span><span>Token</span><span>Price</span><span>Market cap</span><span>Progress</span></div>{data.map((token, index) => <Link key={token.contract_address} href={`/token/${token.contract_address}`} className="grid grid-cols-[56px_1fr_130px_130px_120px] items-center gap-4 border-b border-white/[0.05] px-5 py-4 transition last:border-0 hover:bg-white/[0.03]"><span className="flex items-center gap-2 text-sm text-[#aab4c4]">{index < 3 ? <Crown className={index === 0 ? 'text-[#d8b36e]' : 'text-[#718096]'} /> : null}{String(index + 1).padStart(2, '0')}</span><span className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-[#345d9d] text-[10px] font-semibold">{token.symbol.slice(0, 2).toUpperCase()}</span><span><b className="block text-sm">{token.name}</b><small className="text-[#718096]">${token.symbol} · {token.status}</small></span></span><span className="text-sm">${Number(token.current_price ?? 0).toFixed(6)}</span><span className="text-sm">${Number(token.market_cap ?? 0).toLocaleString()}</span><span className="flex items-center gap-2 text-sm text-[#71d7ba]">{Number(token.progress ?? 0).toFixed(1)}% <ArrowUpRight /></span></Link>)}</div> : <div className="rounded-2xl border border-dashed border-white/15 bg-[#111722] p-16 text-center text-sm text-[#8c98ab]">No indexed tokens are available yet.</div>}</div></main>
}
