'use client'

import { useState } from 'react'
import { Copy, KeyRound, ShieldCheck, Webhook } from 'lucide-react'
import { PageFrame, SectionHeading } from '@/components/app-header'

const scopes = ['tokens:read', 'market:read', 'portfolio:read', 'webhooks:write']

export default function ApiAccessPage() {
  const [created, setCreated] = useState(false)
  const [copied, setCopied] = useState(false)
  const endpoint = 'https://api.lunafad.xyz/v1'
  const copyEndpoint = async () => { await navigator.clipboard?.writeText(endpoint); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <PageFrame active="Settings"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Developer platform · scoped access" title="API & webhooks" description="Build trusted integrations on indexed SVP Chain data without exposing wallet credentials." /><div className="mt-8 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/[0.08] bg-[#101722] p-5"><div className="flex items-center gap-3"><KeyRound className="size-5 text-[#71d7ba]" /><div><h2 className="font-medium">Read-only API access</h2><p className="mt-1 text-xs text-[#71809a]">Keys are scoped, revocable, and never used to sign transactions.</p></div></div><div className="mt-6 flex items-center justify-between rounded-xl border border-white/[0.08] bg-[#0b0f16] px-4 py-3"><code className="text-xs text-[#9de8d1]">{endpoint}</code><button onClick={copyEndpoint} className="rounded-lg border border-white/[0.08] p-2 text-[#aab6c8]" aria-label="Copy API endpoint"><Copy className="size-4" /></button></div><p className="mt-2 text-[11px] text-[#71809a]">{copied ? 'Endpoint copied.' : 'Rate limits and freshness headers are returned on every response.'}</p><div className="mt-6 flex flex-wrap gap-2">{scopes.map(scope => <span key={scope} className="rounded-full border border-[#71d7ba]/20 bg-[#71d7ba]/[0.06] px-2.5 py-1 font-mono text-[10px] text-[#9de8d1]">{scope}</span>)}</div><button onClick={() => setCreated(true)} className="mt-6 rounded-xl bg-[#71d7ba] px-4 py-2.5 text-sm font-medium text-[#07100f]">{created ? 'Key request queued' : 'Request scoped key'}</button></section><section className="space-y-5"><div className="rounded-2xl border border-white/[0.08] bg-[#101722] p-5"><div className="flex items-center gap-3"><Webhook className="size-5 text-[#d9b878]" /><div><h2 className="font-medium">Verified webhooks</h2><p className="mt-1 text-xs text-[#71809a]">Events include delivery IDs, signatures, and indexed freshness.</p></div></div><div className="mt-5 space-y-2 text-xs text-[#aab6c8]"><p className="rounded-lg border border-white/[0.06] px-3 py-2">token.created</p><p className="rounded-lg border border-white/[0.06] px-3 py-2">trade.confirmed</p><p className="rounded-lg border border-white/[0.06] px-3 py-2">indexer.reconciled</p></div></div><div className="rounded-2xl border border-white/[0.08] bg-[#101722] p-5"><ShieldCheck className="size-5 text-[#71d7ba]" /><h2 className="mt-3 font-medium">Trust boundaries</h2><p className="mt-2 text-xs leading-5 text-[#71809a]">Wallet signing, balances, and private keys never pass through this API. Production key persistence requires an authenticated organization.</p></div></section></div></div></PageFrame>
}
