'use client'

import { useState } from 'react'
import { Activity, Database, Gauge, HeartPulse, Radio, RefreshCw, Server, TriangleAlert, type LucideIcon } from 'lucide-react'
import { PageFrame, SectionHeading } from '@/components/app-header'

const metrics: Array<[string, string, string, LucideIcon]> = [['Availability', '—', 'SLO telemetry', Gauge], ['RPC latency', '—', 'Awaiting probe', Radio], ['Indexer lag', '—', 'Block checkpoint', Activity], ['Queue depth', '—', 'Replay telemetry', Database]]
const services: Array<[string, string, string, LucideIcon]> = [['Web application', 'Serving routes and client interactions', 'Operational', HeartPulse], ['Supabase indexer', 'Token, trade, and creator data freshness', 'Awaiting telemetry', Database], ['SVP RPC', 'Chain reads and transaction submission', 'Awaiting probe', Radio], ['Event queue', 'Replay, retry, and reconciliation pipeline', 'Not connected', Server]]

export default function SystemHealthPage() { const [refreshed, setRefreshed] = useState(false); return <PageFrame><SectionHeading eyebrow="Reliability center" title="System health" description="Operational visibility for availability, RPC latency, indexer lag, queue health, and transaction success. Metrics remain honest until telemetry is connected." /><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#71d7ba]/20 bg-[#71d7ba]/[0.05] px-5 py-4"><div className="flex items-center gap-3"><div className="size-2 rounded-full bg-[#71d7ba] shadow-[0_0_18px_#71d7ba]" /><div><p className="text-sm font-medium">Frontend operational</p><p className="mt-1 text-xs text-[#71809a]">Last checked from this preview environment</p></div></div><button onClick={() => setRefreshed(true)} className="flex items-center gap-2 rounded-lg border border-white/[0.1] px-3 py-2 text-xs text-[#b9c3d1]"><RefreshCw className="size-3.5" />{refreshed ? 'Checked now' : 'Refresh probes'}</button></div><div className="mt-6 grid gap-4 md:grid-cols-4">{metrics.map(([label, value, hint, Icon]) => <div key={String(label)} className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><Icon className="size-4 text-[#8eb1eb]" /><p className="mt-5 text-xs text-[#71809a]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-2 text-[11px] text-[#71809a]">{hint}</p></div>)}</div><section className="mt-6 rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="flex items-center gap-2"><TriangleAlert className="size-4 text-[#d9b878]" /><p className="text-sm font-medium">Telemetry coverage</p></div><div className="mt-5 grid gap-3">{services.map(([name, body, status, Icon]) => <div key={String(name)} className="flex items-center gap-4 rounded-xl border border-white/[0.06] bg-white/[0.02] p-4"><Icon className="size-4 shrink-0 text-[#8eb1eb]" /><div className="min-w-0 flex-1"><p className="text-sm">{name}</p><p className="mt-1 text-xs text-[#71809a]">{body}</p></div><span className="shrink-0 text-[10px] uppercase tracking-wider text-[#d9b878]">{status}</span></div>)}</div></section></PageFrame> }
