'use client'

import Link from 'next/link'
import useSWR from 'swr'
import { ArrowUpRight, BriefcaseBusiness, Eye, History, RefreshCw, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import { useWalletIdentity, walletAddressLabel } from '@/lib/web3/wallet-store'

type Position = { token_address: string; balance: number; usd_value: number; avg_buy_price: number; pnl_24h: number }
type Activity = { token_address: string; side: string; price: number | null; amount: number | null; tx_hash: string; created_at: string }

export default function PortfolioPage() {
  const supabase = getSupabaseBrowserClient()
  const identity = useWalletIdentity()
  const wallet = identity.address
  const [tab, setTab] = useState<'holdings' | 'watchlist' | 'activity'>('holdings')
  const key = supabase && wallet ? ['portfolio', wallet] : null
  const { data: positions, error, isLoading, mutate } = useSWR<Position[]>(key, async () => { const { data, error } = await supabase!.from('user_portfolio').select('token_address,balance,usd_value,avg_buy_price,pnl_24h').eq('user_address', wallet!).order('usd_value', { ascending: false }); if (error) throw error; return (data ?? []) as Position[] })
  const { data: watchlist } = useSWR(supabase && wallet ? ['portfolio-watchlist', wallet] : null, async () => { const { data, error } = await (supabase!.from('user_watchlist') as any).select('token_address,added_at').eq('user_address', wallet!).order('added_at', { ascending: false }); if (error) throw error; return data ?? [] })
  const { data: activity } = useSWR<Activity[]>(supabase && wallet ? ['portfolio-activity', wallet] : null, async () => { const { data, error } = await supabase!.from('token_trades').select('token_address,side,price,amount,tx_hash,created_at').eq('trader', wallet!).order('created_at', { ascending: false }).limit(50); if (error) throw error; return (data ?? []) as Activity[] })
  const total = (positions ?? []).reduce((sum, row) => sum + Number(row.usd_value ?? 0), 0)
  const pnl = (positions ?? []).reduce((sum, row) => sum + Number(row.pnl_24h ?? 0), 0)
  return <main className="min-h-screen bg-[#0b0f16] px-5 pb-16 pt-28 text-white lg:px-10"><div className="mx-auto max-w-6xl"><header className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-semibold tracking-[0.24em] text-[#71d7ba]">ACCOUNT CENTER</p><h1 className="text-4xl font-semibold tracking-tight">Portfolio</h1><p className="mt-3 max-w-xl text-sm text-[#8c98ab]">Track balances, watchlist, and confirmed activity from one workspace.</p>{wallet && <p className="mt-2 font-mono text-[11px] text-[#71d7ba]">Active wallet · {walletAddressLabel(wallet)}</p>}{identity.status === 'wrong-network' && <p className="mt-2 text-xs text-[#e8b86a]">Switch to SVP Chain Testnet to read this portfolio.</p>}</div><button onClick={() => { void mutate() }} disabled={!wallet || isLoading} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm text-[#b9c3d1] disabled:cursor-not-allowed disabled:opacity-50"><RefreshCw className={`size-4 ${isLoading ? 'animate-spin' : ''}`} />Refresh</button></header><div className="mb-8 grid gap-4 md:grid-cols-3"><Metric label="Portfolio value" value={wallet ? `$${total.toLocaleString(undefined, { maximumFractionDigits: 2 })}` : 'Connect wallet'} /><Metric label="24h PNL" value={wallet ? `${pnl >= 0 ? '+' : ''}$${pnl.toLocaleString(undefined, { maximumFractionDigits: 2 })}` : '—'} tone={pnl >= 0 ? 'positive' : 'negative'} /><Metric label="Positions" value={wallet ? String(positions?.length ?? 0) : '—'} /></div><section className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-medium">Portfolio workspace</h2><p className="mt-1 text-xs text-[#718096]">Indexed from confirmed on-chain activity.</p></div><div className="flex rounded-lg border border-white/10 p-1">{([{ key: 'holdings', label: 'Holdings', icon: WalletCards }, { key: 'watchlist', label: 'Watchlist', icon: Eye }, { key: 'activity', label: 'Activity', icon: History }] as const).map(item => { const Icon = item.icon; return <button key={item.key} onClick={() => setTab(item.key)} className={`flex items-center gap-2 rounded-md px-3 py-2 text-xs ${tab === item.key ? 'bg-[#345d9d] text-white' : 'text-[#8c98ab]'}`}><Icon className="size-3.5" />{item.label}</button> })}</div></div>{!wallet ? <Empty title="Connect a wallet to view your portfolio" body="Connect the wallet from the header to load wallet-scoped positions, watchlist, and confirmed activity." /> : tab === 'holdings' ? <Holdings positions={positions} isLoading={isLoading} error={error} /> : tab === 'watchlist' ? <Watchlist rows={watchlist ?? []} /> : <ActivityTable rows={activity ?? []} />}</section></div></main>
}
function Holdings({ positions, isLoading, error }: { positions?: Position[]; isLoading: boolean; error?: Error }) { if (isLoading) return <State text="Loading positions…" />; if (error) return <Empty title="Portfolio unavailable" body="The portfolio snapshot could not be read. Try refreshing." />; if (!positions?.length) return <Empty title="No indexed positions yet" body="Buy a token on SVP Chain and your confirmed position will appear here." />; return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-white/[0.08] text-xs uppercase tracking-wider text-[#718096]"><tr><th className="pb-3">Token</th><th className="pb-3">Balance</th><th className="pb-3">Value</th><th className="pb-3">Avg. entry</th><th className="pb-3">24h PNL</th><th /></tr></thead><tbody>{positions.map(row => <tr key={row.token_address} className="border-b border-white/[0.05] last:border-0"><td className="py-4 font-mono text-xs">{row.token_address.slice(0, 8)}…{row.token_address.slice(-6)}</td><td className="py-4">{Number(row.balance).toLocaleString()}</td><td className="py-4">${Number(row.usd_value).toLocaleString(undefined, { maximumFractionDigits: 2 })}</td><td className="py-4">${Number(row.avg_buy_price).toFixed(5)}</td><td className={Number(row.pnl_24h) >= 0 ? 'py-4 text-[#71d7ba]' : 'py-4 text-[#e87984]'}>{Number(row.pnl_24h) >= 0 ? '+' : ''}${Number(row.pnl_24h).toFixed(2)}</td><td className="py-4 text-right"><Link href={`/token/${row.token_address}`} className="text-[#8eb1eb]" aria-label="Open token"><ArrowUpRight className="size-4" /></Link></td></tr>)}</tbody></table></div> }
function Watchlist({ rows }: { rows: Array<{ token_address: string; added_at: string }> }) { if (!rows.length) return <Empty title="Your watchlist is empty" body="Save tokens from their detail page to monitor them here." />; return <div className="grid gap-3 sm:grid-cols-2">{rows.map(row => <Link key={row.token_address} href={`/token/${row.token_address}`} className="flex items-center justify-between rounded-xl border border-white/[0.07] p-4 hover:bg-white/[0.03]"><span className="font-mono text-xs">{row.token_address.slice(0, 12)}…{row.token_address.slice(-8)}</span><ArrowUpRight className="size-4 text-[#8eb1eb]" /></Link>)}</div> }
function ActivityTable({ rows }: { rows: Activity[] }) { if (!rows.length) return <Empty title="No confirmed activity yet" body="Confirmed buys, sells, and other indexed trades will appear here." />; return <div className="space-y-2">{rows.map((row, index) => <Link key={`${row.tx_hash}-${index}`} href={`/token/${row.token_address}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/[0.07] p-4 hover:bg-white/[0.03]"><div><span className={row.side === 'buy' ? 'text-[#71d7ba]' : 'text-[#e87984]'}>{row.side.toUpperCase()}</span><span className="ml-3 font-mono text-xs text-[#8c98ab]">{row.token_address.slice(0, 10)}…</span></div><div className="text-right text-xs text-[#8c98ab]">{Number(row.amount ?? 0).toLocaleString()} @ {Number(row.price ?? 0).toFixed(6)}<br />{new Date(row.created_at).toLocaleString()}</div></Link>)}</div> }
function Metric({ label, value, tone = 'default' }: { label: string; value: string; tone?: string }) { return <div className="rounded-2xl border border-white/[0.08] bg-[#111722] p-5"><p className="text-xs text-[#718096]">{label}</p><p className={`mt-3 text-2xl font-semibold ${tone === 'positive' ? 'text-[#71d7ba]' : tone === 'negative' ? 'text-[#e87984]' : 'text-white'}`}>{value}</p></div> }
function Empty({ title, body }: { title: string; body: string }) { return <div className="flex flex-col items-center justify-center py-14 text-center"><BriefcaseBusiness className="mb-4 text-[#718096]" /><h3 className="font-medium">{title}</h3><p className="mt-2 max-w-md text-sm text-[#718096]">{body}</p></div> }
function State({ text }: { text: string }) { return <p className="py-12 text-center text-sm text-[#8c98ab]">{text}</p> }
