'use client'

import Link from 'next/link'
import { use, useEffect, useMemo, useState } from 'react'
import useSWR from 'swr'
import { Copy, ExternalLink, Star, ArrowDownToLine, ArrowUpFromLine, Activity } from 'lucide-react'
import { useBondingCurve } from '@/lib/hooks/use-bonding-curve'
import { useTerminalChart } from '@/lib/hooks/use-terminal-chart'
import { explorerAddress, shortenAddress, type Timeframe } from '@/lib/contracts/config'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import { useTokenMetadata } from '@/lib/hooks/use-token-metadata'
import { TerminalChart } from '@/components/token/terminal-chart'

const timeframes: Timeframe[] = ['1m', '5m', '15m', '1h', '4h', '1d', '1w']
type Trade = { price: number; volume: number; side: string; trader: string; tx_hash: string; created_at: string }

export default function TokenDetailPage({ params }: { params: Promise<{ address: string }> }) {
  const { address: rawAddress } = use(params)
  const address = rawAddress as `0x${string}`
  const supabase = getSupabaseBrowserClient()
  const [timeframe, setTimeframe] = useState<Timeframe>('1h')
  const [tab, setTab] = useState<'overview' | 'trades' | 'contract'>('overview')
  const [watchlisted, setWatchlisted] = useState(false)
  const [userId, setUserId] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const { data: curve, loading: curveLoading } = useBondingCurve(address)
  const { candles, live, loading: candlesLoading } = useTerminalChart(address, timeframe)
  const { data: token, isLoading: tokenLoading } = useTokenMetadata(address)
  const { data: trades } = useSWR<Trade[]>(supabase ? ['token-trades', address] : null, async () => { const { data } = await supabase!.from('token_trades').select('price,volume,side,trader,tx_hash,created_at').eq('token_address', address).order('created_at', { ascending: false }).limit(25); return (data ?? []) as Trade[] })

  useEffect(() => { if (!supabase) return; supabase.auth.getUser().then(({ data }) => { setUserId(data.user?.id ?? null); if (data.user) (supabase.from('user_watchlist') as any).select('token_address').eq('user_address', data.user.id).eq('token_address', address).maybeSingle().then(({ data: row }: { data: unknown }) => setWatchlisted(Boolean(row))) }) }, [address, supabase])
  async function toggleWatchlist() { if (!supabase || !userId) return; if (watchlisted) await (supabase.from('user_watchlist') as any).delete().eq('user_address', userId).eq('token_address', address); else await (supabase.from('user_watchlist') as any).insert({ user_address: userId, token_address: address }); setWatchlisted(value => !value) }
  async function copyAddress() { await navigator.clipboard.writeText(address); setCopied(true); window.setTimeout(() => setCopied(false), 1400) }

  const last = candles.at(-1)
  const price = curve?.price ?? token?.current_price ?? last?.close
  const change = useMemo(() => { if (candles.length < 2) return null; const previous = candles.at(-2)?.close ?? 0; return previous ? ((candles.at(-1)!.close - previous) / previous) * 100 : null }, [candles])
  const displayName = token?.name ?? shortenAddress(address, 6)
  return <main className="min-h-screen bg-[#0b0f16] px-5 py-8 text-white lg:px-10"><div className="mx-auto max-w-7xl"><Link href="/explore" className="text-xs text-[#8eb1eb]">← Back to Explore</Link><header className="mt-8 flex flex-wrap items-center gap-4"><div className="flex size-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#345d9d] to-[#71d7ba] text-lg font-bold">{token?.symbol?.slice(0, 2) ?? 'SV'}</div><div><div className="flex items-center gap-2"><p className="text-[11px] uppercase tracking-wider text-[#71d7ba]">{token?.status ?? 'On-chain token'}</p>{token?.verified && <span className="rounded-full bg-[#71d7ba]/10 px-2 py-0.5 text-[10px] text-[#71d7ba]">Verified</span>}</div><h1 className="text-3xl font-semibold">{tokenLoading ? 'Loading token…' : displayName}</h1><button onClick={copyAddress} className="flex items-center gap-1 text-xs text-[#71809a] hover:text-white">${token?.symbol ?? 'TOKEN'} · {shortenAddress(address, 6)} <Copy className="size-3" />{copied && <span className="text-[#71d7ba]">Copied</span>}</button></div><div className="ml-auto flex gap-2"><button onClick={toggleWatchlist} disabled={!userId} className={`rounded-lg border p-2 ${watchlisted ? 'border-[#71d7ba]/50 text-[#71d7ba]' : 'border-white/10 text-white'} disabled:cursor-not-allowed disabled:opacity-50`} aria-label={watchlisted ? 'Remove from watchlist' : 'Add to watchlist'}><Star className="size-4" fill={watchlisted ? 'currentColor' : 'none'} /></button><a href={explorerAddress(address)} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs">Explorer <ExternalLink className="size-3" /></a></div></header>

<section className="mt-8 grid gap-5 lg:grid-cols-[1fr_340px]"><div className="rounded-xl border border-white/10 bg-[#111722] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-2xl font-semibold">{curveLoading ? 'Loading…' : price ? `${Number(price).toFixed(6)} SVP` : '—'}</p><p className={`mt-1 flex items-center gap-2 text-xs ${change && change >= 0 ? 'text-[#71d7ba]' : 'text-[#e87984]'}`}><Activity className="size-3" />{change === null ? 'Awaiting indexed candle history' : `${change >= 0 ? '+' : ''}${change.toFixed(2)}% since previous candle`}</p></div><div className="flex items-center gap-1 rounded-lg border border-white/10 p-1">{timeframes.map(item => <button key={item} onClick={() => setTimeframe(item)} className={`rounded px-2 py-1 text-[10px] ${timeframe === item ? 'bg-[#345d9d] text-white' : 'text-[#71809a] hover:text-white'}`}>{item}</button>)}</div></div><div className="mt-5"><TerminalChart candles={candles} live={live && !candlesLoading} /></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-white/[0.06] pt-4 sm:grid-cols-4"><Metric label="Market cap" value={formatNumber(token?.market_cap)} /><Metric label="Volume 24h" value={formatNumber(token?.volume_24h)} /><Metric label="Curve progress" value={`${Number(token?.progress ?? curve?.progress ?? 0).toFixed(1)}%`} /><Metric label="Status" value={token?.status ?? '—'} /></div></div><TradePanel price={typeof price === 'number' ? price : Number(price ?? 0)} /></section>

<section className="mt-5 rounded-xl border border-white/10 bg-[#111722] p-5"><div className="flex gap-5 border-b border-white/[0.06]">{(['overview', 'trades', 'contract'] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 pb-3 text-sm capitalize ${tab === item ? 'border-[#71d7ba] text-white' : 'border-transparent text-[#71809a]'}`}>{item}</button>)}</div>{tab === 'overview' && <div className="grid gap-6 pt-5 md:grid-cols-2"><div><p className="text-xs uppercase tracking-wider text-[#71809a]">Description</p><p className="mt-2 text-sm leading-6 text-[#b9c3d1]">{token?.description || 'No indexed description is available for this token yet.'}</p></div><div><p className="text-xs uppercase tracking-wider text-[#71809a]">Creator</p><a href={explorerAddress(token?.creator_address ?? address)} target="_blank" rel="noreferrer" className="mt-2 block text-sm text-[#8eb1eb]">{shortenAddress(token?.creator_address ?? address, 8)}</a></div></div>}{tab === 'trades' && <TradeTable trades={trades ?? []} />}{tab === 'contract' && <div className="grid gap-3 pt-5 text-sm text-[#b9c3d1]"><p>Token contract <span className="ml-2 font-mono text-[#8eb1eb]">{shortenAddress(address, 10)}</span></p><p>Network <span className="ml-2 text-white">SVP Chain</span></p><p>Data source <span className="ml-2 text-white">On-chain reads + Supabase index</span></p></div>}</section></div></main>
}

function TradePanel({ price }: { price?: number }) { return <aside className="rounded-xl border border-white/10 bg-[#111722] p-5"><div className="flex items-center justify-between"><h2 className="font-medium">Trade token</h2><span className="text-[10px] uppercase tracking-wider text-[#71809a]">Wallet required</span></div><div className="mt-5 flex rounded-lg border border-white/10 p-1"><button className="flex-1 rounded-md bg-[#345d9d] py-2 text-xs">Buy</button><button className="flex-1 py-2 text-xs text-[#71809a]">Sell</button></div><label className="mt-5 block text-xs text-[#71809a]">You pay</label><div className="mt-2 flex items-center justify-between rounded-lg border border-white/10 bg-[#0b0f16] px-3 py-3 text-sm"><span>0.00</span><span className="text-[#b9c3d1]">SVP</span></div><p className="mt-3 text-xs text-[#71809a]">Spot price {price ? `${Number(price).toFixed(6)} SVP` : '—'}</p><button disabled className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-[#345d9d] py-3 text-sm font-medium opacity-50"><ArrowUpFromLine className="size-4" />Connect wallet to trade</button><p className="mt-3 text-center text-[11px] leading-5 text-[#71809a]">Quotes, slippage, fees, and approval will appear after wallet connection.</p></aside> }
function TradeTable({ trades }: { trades: Trade[] }) { if (!trades.length) return <p className="py-10 text-center text-sm text-[#71809a]">No indexed trades yet.</p>; return <div className="overflow-x-auto pt-4"><table className="w-full text-left text-xs"><thead className="text-[#71809a]"><tr><th className="pb-3">Side</th><th className="pb-3">Price</th><th className="pb-3">Volume</th><th className="pb-3">Trader</th><th className="pb-3">Tx</th></tr></thead><tbody>{trades.map(trade => <tr key={`${trade.tx_hash}-${trade.created_at}`} className="border-t border-white/[0.05]"><td className={`py-3 uppercase ${trade.side === 'buy' ? 'text-[#71d7ba]' : 'text-[#e87984]'}`}>{trade.side}</td><td className="py-3">{Number(trade.price).toFixed(6)}</td><td className="py-3">{Number(trade.volume).toLocaleString()}</td><td className="py-3 font-mono text-[#8c98ab]">{shortenAddress(trade.trader, 5)}</td><td className="py-3 font-mono text-[#8eb1eb]">{shortenAddress(trade.tx_hash, 5)}</td></tr>)}</tbody></table></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-[#718096]">{label}</p><p className="mt-1 truncate text-sm font-medium text-[#e8edf4]">{value}</p></div> }
function formatNumber(value: number | null | undefined) { return value == null ? '—' : `$${Number(value).toLocaleString(undefined, { maximumFractionDigits: 2 })}` }
